services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: homework30
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d homework30"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/homework30
    command: ["python", "homework_30_1.py", "2", "+", "3"]

  tests:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/homework30
    volumes:
      - ./allure-results:/app/allure-results
    command: ["pytest", "-v", "--alluredir=allure-results"]

volumes:
  postgres_data:
